### PR TITLE
Ca 215080

### PR DESCRIPTION
**Pull request by swathicitrix**

### CODE REVIEW

**Comment by chandrikas** [comment]
@swathicitrix: This pull request contains a lot of unrelated commits. Could you please correct it?

**Comment by swathicitrix** [comment]
Chandrika, 
Currently i am facing build issues when i am trying to build these changes in a new branch related to 
coverity tool. 
Once i resolve them i will pull the new branch changes on to the same pull request.

**Comment by swathicitrix** [comment]
I resolved the issue with unrelated commits.

**Comment by MarkSymsCtx** [comment]
Looks fine now, please add to the patchqueue

**Pull request closed without merging**
