### PR TITLE
CA-220042: sigact.sa_mask is not initialized (CID:57552)

### PR DESCRIPTION
**Pull request by geosharath**
Signed-off-by: Sharath Babu sharath.babu@citrix.com

### CODE REVIEW

**Comment by MarkSymsCtx** [comment]
Looks good

**Comment by MarkSymsCtx** [comment]
This exposed another suspect usage of sigemptyset, so we should fix that as well.

**Comment by MarkSymsCtx** [comment]
Update looks good.

**Comment by germanop** [comment]
The patch reviewed and the patch we have been testing do not match.

I wonder what we have been testing so far.
Once this is clarified let's remember to port the changes to the release branch

**Comment by MarkSymsCtx** [comment]
Merged separately, so closing.

**Pull request closed without merging**
